Algoritmo "A grana tá na conta EX8"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/01/2025
Var
// Seção de Declarações das variáveis 
D , R : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreval ("Digite o valor em Dolar")
 leia(D)
 
 R := D * 6.1
 
 escreval ("você tem  R$", R)

Fimalgoritmo