Algoritmo "Pousada asa branca EX7"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/01/2025
Var
// Seção de Declarações das variáveis 
  K : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  escreval("Digite o peço do seu prato")
  leia(K)
  
  K := K * 20
  
   escreval ("O valor que deve ser pago é de R$",K)

Fimalgoritmo