Algoritmo "Triplicando seu dinheiro EX3"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/01/2025
Var
// Seção de Declarações das variáveis 
  N: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    escreval("Digite seu valor:")
    leia(N)
    
    N := N * 3
    
    escreval("O triplo do seu valor é", N)

Fimalgoritmo