Algoritmo "bora meu fi EX6"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/01/2025
Var
// Seção de Declarações das variáveis 
 N,S: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  repita
  
  escreval("Digite o valor")
  leia(N)
  
  se (N > 0) entao
  S := S + N
  senao
  fimse
  
  ate (N = 0)
  
  escreval("A soma dos valores é", S)

Fimalgoritmo