Algoritmo "Passa ou não passa"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/01/2025
Var
// Seção de Declarações das variáveis
N1,N2,N3,R : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
 escreva ("Digite as três notas")
 leia(N1,N2,N3)
 
 R <- ( N1 + N2 + N3 ) / 3
 
 escreva ("Sua nota é", R)


Fimalgoritmo